spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/SpringStart
    username: postgres
    password: 0018
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/

  servlet:
    multipart:
      max-file-size: 10MB

  web:
    resources:
      static-locations: classpath:/static/

files:
  upload:
    directory: D:\working\jav\StartSpring\src\main\resources\files
